"""add delivery photo to orders

Revision ID: 3c8437e96e31
Revises: c9a63b9d14ae
Create Date: 2026-07-29 04:32:53.057272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8437e96e31'
down_revision: Union[str, Sequence[str], None] = 'c9a63b9d14ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_photo')
    # ### end Alembic commands ###
