"""add created_at to orders

Revision ID: e4326f994324
Revises: 910846cbee10
Create Date: 2026-07-29 01:56:24.598364

"""
from typing import Sequence, Union
from sqlalchemy.sql import func
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4326f994324'
down_revision: Union[str, Sequence[str], None] = '910846cbee10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "orders",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=func.now()
        )
    )

    # Opcional: elimina el valor por defecto para que
    # SQLAlchemy use datetime.utcnow en los nuevos registros.
    op.alter_column(
        "orders",
        "created_at",
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
